### ISSUE TITLE
production can't access the pocketbase instance

### ISSUE THREAD

**Issue by cntrvsy** [coollabsio/pocketbase#51]
im running coolify, pocketbase and sveltekit all running on one server but im running into a problem where on my local environment its fine users, can sign in/sign up, perform CRUD etc  (same env variables ) but on production it is not, in the browser im getting an uncaught promise -> TextField.3SpA9uL8.js:3  Uncaught (in promise) R: No form data returned from ActionResult. Make sure you return { form } in the form actions. looking at my logs from sveltekit im getting "PB run ERROR! (signIn) ClientResponseError 0: Something went wrong while processing your request." from my form action. looking at my pocketbase logs im not seeing an error log. leading me to believe i haven't configured something correctly as the connection seems to not be established and times out. i installed pocketbase from the coolify gui and i havent touched the docker compose file. any guidance will be appreciated.

here is my form action logic if its useful
```
  signIn: async ({ request, locals: { pb } }) => {
    const signIn_Form = await superValidate(request, zod(SignInSchema));

    console.log('Sign In', signIn_Form);
    
    // error checking for the form itself
    if(!signIn_Form.valid) {

      return fail(400, {message:'Invalid signIn Form Submission',errors: signIn_Form.errors,signIn_Form});

    } else {
        const { email, password } = signIn_Form.data;

        // sending it to PB
        try {
          await pb.collection('users').authWithPassword(
            email,
            password,
          )
          console.log("PB run(signIn)")
        } catch (err) {
          console.log("PB run ERROR(signIn)")
          console.log(err)
          //if PB returns error
          if(err){
            
            if (err instanceof ClientResponseError && err.status === 400) {
              console.log(error)
              return message(signIn_Form,{text: 'Invalid Credentials, Try again.', status: 401});
            }
            return fail(500, { message: 'Server error. Try again later.'})
          }
        }

        // Successful sign-In, update the store and dispatch custom event.
        redirect(303, '/Portal')
      //return message(signIn_Form, {text: 'I posted, refresh the page'});
    }
  },
```

**Comment by leuwenn** [comment]
Hi,
You should check your PocketBase URL/environment variables. And the error typically pops up if nothing (or the wrong data) is returned from the form action.
Make sure your form action always returns the form object or a redirect.
For a successful sign-in, you probably want to throw redirect(303, '/Portal').
For errors, always return fail(400, { form: signIn_Form, ... }) or use the appropriate superforms helper like return message(...).

**Comment by cntrvsy** [comment]
after digging around, it seems i just cannot seem to connect to the pocketbase instance from my production environment (both the app and pocketbase are running on localhost),(yes my env variables are fine, yes my form actions are fine) the problem lies here. 
```
2025-01-02T11:52:58.521987652Z PB run ERROR! (signIn) ClientResponseError 0: Something went wrong while processing your request.
2025-01-02T11:52:58.525901302Z     at file:///app/node_modules/pocketbase/dist/pocketbase.es.mjs:1:32687
2025-01-02T11:52:58.525938613Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-02T11:52:58.525944023Z     at async signIn (file:///app/build/server/chunks/31-uMa5Z4Dv.js:30:9)
2025-01-02T11:52:58.526667127Z     at async handle_action_json_request (file:///app/build/server/index.js:1385:18)
2025-01-02T11:52:58.526684377Z     at async resolve2 (file:///app/build/server/index.js:3802:24)
2025-01-02T11:52:58.526688607Z     at async Object.handle (file:///app/build/server/chunks/hooks.server-DGwYSmZA.js:22:20)
2025-01-02T11:52:58.526692658Z     at async respond (file:///app/build/server/index.js:3694:22)
2025-01-02T11:52:58.526696468Z     at async Array.ssr (file:///app/build/handler.js:1270:3) {
2025-01-02T11:52:58.526701758Z   url: '',
2025-01-02T11:52:58.526705788Z   status: 0,
2025-01-02T11:52:58.526709908Z   response: {},
2025-01-02T11:52:58.526713908Z   isAbort: false,
2025-01-02T11:52:58.526717508Z   originalError: TypeError: fetch failed
2025-01-02T11:52:58.526723058Z       at node:internal/deps/undici/undici:12618:11
2025-01-02T11:52:58.526727699Z       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-02T11:52:58.526731439Z       at async signIn (file:///app/build/server/chunks/31-uMa5Z4Dv.js:30:9)
2025-01-02T11:52:58.526735709Z       at async handle_action_json_request (file:///app/build/server/index.js:1385:18)
2025-01-02T11:52:58.526739549Z       at async resolve2 (file:///app/build/server/index.js:3802:24)
2025-01-02T11:52:58.526802741Z       at async Object.handle (file:///app/build/server/chunks/hooks.server-DGwYSmZA.js:22:20)
2025-01-02T11:52:58.526807451Z       at async respond (file:///app/build/server/index.js:3694:22)
2025-01-02T11:52:58.526811641Z       at async Array.ssr (file:///app/build/handler.js:1270:3) {
2025-01-02T11:52:58.526815891Z     cause: Error: getaddrinfo ENOTFOUND <INSERT THE POCKETBASE HTTPS URL HERE>
2025-01-02T11:52:58.526820111Z         at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
2025-01-02T11:52:58.526823901Z       errno: -3008,
2025-01-02T11:52:58.526828031Z       code: 'ENOTFOUND',
2025-01-02T11:52:58.526832262Z       syscall: 'getaddrinfo',
2025-01-02T11:52:58.526836062Z       hostname: '<INSERT THE POCKETBASE HTTPS URL HERE>'
2025-01-02T11:52:58.526839842Z     }
2025-01-02T11:52:58.526843842Z   }
2025-01-02T11:52:58.526847572Z }
``` 
i have even tried turning on predefined network on and trying the actual internal ip address docker gave my container still no dice, added a custom docker options to add it to the same network still no dice, hard coded the env, still no dice. Again any help/ guidance will be appreciated.

**Comment by cntrvsy** [comment]
okay i found out the issue ,so ill drop it here for all the coolify newbies like me. the issue was my ENV variable. Once you have selected the predefined network option, head over to your MAIN terminal (on the main side bar on the left) and type "docker network ls" and try to identify which one of the containers is your pocketbase instance. just to be sure you can run "docker network inspect <CONTAINER NAME HERE>" and if you scroll abit, under Containers you should see "name": "pocketbase-<BUNCH OF LETTERS/NUMBERS>". Take that value and THEN use it as your env variable adding :8080 to the end of it. so it should be something like DATABASE_URL = "http://pocketbase-sdc345fvAsdvfgb567c:8080/". you may have to open that port as well on your VPS. hopefully this helps.
